// The text deliverables — node index, activity lists, ICOM tables, the concept
// registry and the rule check — as Markdown or as a self-contained HTML
// document. A port of src/io/report.js.
//
// The Concepts table is the part of the report read by something other than a
// person, so it is kept to the web app's text exactly. The HTML is not a
// general Markdown renderer: it is the web app's own few-rule converter, quirks
// included (a table whose first row is all blank cells, like the header-field
// table, loses that row as though it were the separator), because a report
// saved from either front-end must be the same file.

import Foundation

public enum Report {
    /// `toMarkdown(model)`. `generatedOn` fills the date in the closing
    /// "_Generated by IDEF0 Modeler on …._" line, and nothing else.
    public static func markdown(_ model: IDEF0Model, generatedOn: String = todayISO()) -> String {
        var lines: [String] = []

        lines += ["# \(model.title.isEmpty ? "Untitled IDEF0 Model" : model.title)", ""]
        lines += ["| | |", "|---|---|"]
        lines.append("| Author | \(md(model.author)) |")
        lines.append("| Project | \(md(model.project)) |")
        lines.append("| Status | \(md(model.status)) |")
        lines.append("| Created | \(md(model.created)) |")
        lines.append("| Revised | \(md(model.revised)) |")
        lines.append("")
        // Purpose and viewpoint are written raw — trimmed, not md()-escaped — as the web app does.
        lines += ["**Purpose.** " + or(jsTrim(model.purpose), "_not stated_"), ""]
        lines += ["**Viewpoint.** " + or(jsTrim(model.viewpoint), "_not stated_"), ""]

        lines += ["## Node index", ""]
        // The web app throws here on a model without a context diagram; a
        // deserialized model always has one.
        // Every box is listed; a detail diagram already on the path — a
        // decomposition cycle, reported by the rule check — is not entered again.
        var path = Set<JSStringKey>()
        func walkIndex(_ dg: Diagram, _ depth: Int) {
            path.insert(JSStringKey(dg.id))
            for b in dg.sortedBoxes {
                lines.append("\(String(repeating: "  ", count: depth))- **\(boxNode(dg, b))** \(or(b.name, "_(unnamed)_"))")
                if let child = model.childDiagram(of: b), !path.contains(JSStringKey(child.id)) { walkIndex(child, depth + 1) }
            }
            path.remove(JSStringKey(dg.id))
        }
        if let ctx = model.contextDiagram { walkIndex(ctx, 0) }
        lines.append("")

        lines += ["## Diagrams", ""]
        for (dg, _) in model.diagramTree() {
            lines += ["### \(dg.node) — \(or(dg.title, model.title))", ""]
            if !dg.cNumber.isEmpty { lines += ["C-number: `\(dg.cNumber)`", ""] }

            lines += ["**Activities**", ""]
            lines += ["| Box | Node | Name | Decomposed |", "|---|---|---|---|"]
            for b in dg.sortedBoxes {
                let decomposed = model.childDiagram(of: b) == nil ? "no" : "yes"
                lines.append("| \(b.number) | \(boxNode(dg, b)) | \(or(md(b.name), "_(unnamed)_")) | \(decomposed) |")
            }
            lines.append("")

            let codes = model.exactIcomCodes(dg)
            lines += ["**Arrows**", ""]
            lines += ["| Role | Label | From | To | ICOM | Tunnel |", "|---|---|---|---|---|---|"]
            for a in dg.arrows {
                let code = or(codes[JSStringKey("\(a.id):from")] ?? "", codes[JSStringKey("\(a.id):to")] ?? "")
                let tunnel = a.tunnelFrom || a.tunnelTo ? "yes" : ""
                lines.append("| \(a.role.label) | \(or(md(a.label), "_(unlabelled)_")) | \(endDesc(dg, a.from)) | \(endDesc(dg, a.to)) | \(code) | \(tunnel) |")
            }
            lines.append("")

            let notes = dg.sortedBoxes.filter { !jsTrim($0.note).isEmpty }
            if !notes.isEmpty {
                lines += ["**Notes**", ""]
                for b in notes { lines.append("- **\(boxNode(dg, b))** — \(md(b.note))") }
                lines.append("")
            }
        }

        if !model.glossary.isEmpty {
            // The concept registry, with where each concept is used.
            let usage = model.exactConceptUsage()
            lines += ["## Concepts", ""]
            lines += ["| Term | Kind | Used | Occurs on | Definition |", "|---|---|---|---|---|"]
            for g in model.glossary {
                let occ = model.occurrencesOf(g.id)
                let whereUsed = occ.map { "\($0.node)\u{00A0}\($0.kind == .box ? "act" : "obj")" }.joined(separator: ", ")
                let used = usage[JSStringKey(g.id)] ?? 0
                lines.append("| \(md(g.term)) | \(g.kind) | \(used) | \(or(whereUsed, "—")) | \(or(md(g.definition), "_undefined_")) |")
            }
            lines.append("")

            let drift = model.driftedOccurrences()
            if !drift.isEmpty {
                lines += ["### Label elaboration", ""]
                lines += ["Places where the drawn text differs from the concept it denotes — legitimate under FIPS 183 §3.3.2.4.", ""]
                lines += ["| Where | Reads | Concept |", "|---|---|---|"]
                for d in drift {
                    lines.append("| \(d.node) \(d.kind == .box ? "activity" : "arrow") | \(md(d.text)) | \(md(d.term)) |")
                }
                lines.append("")
            }

            let unused = model.unusedConcepts()
            if !unused.isEmpty {
                lines += ["_\(unused.count) concept(s) defined but not used: \(unused.map { md($0.term) }.joined(separator: ", "))._", ""]
            }
        }

        let issues = validate(model)
        let s = summarize(issues)
        lines += ["## Rule check", ""]
        lines += ["\(s.errors) error(s), \(s.warnings) warning(s).", ""]
        if !issues.isEmpty {
            lines += ["| Severity | Diagram | Rule | Detail |", "|---|---|---|---|"]
            for i in issues {
                let node = or(model.diagram(i.diagramId)?.node ?? "", "—")
                lines.append("| \(i.severity.rawValue) | \(node) | `\(i.code)` | \(md(i.message)) |")
            }
            lines.append("")
        }

        lines += ["---", "", "_Generated by IDEF0 Modeler on \(generatedOn)._"]
        return lines.joined(separator: "\n")
    }

    /// `toHtml(model)`: the Markdown report through `markdownToHtml`, in a page
    /// with its own stylesheet so the file stands alone.
    public static func html(_ model: IDEF0Model, generatedOn: String = todayISO()) -> String {
        let body = markdownToHtml(markdown(model, generatedOn: generatedOn))
        return """
            <!doctype html><html><head><meta charset="utf-8"><title>\(escapeXml(model.title)) — IDEF0 report</title>
            <style>
            body{font:14px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
              max-width:60rem;margin:2.5rem auto;padding:0 1.5rem;color:#1c2024}
            h1{font-size:1.8rem;border-bottom:2px solid #1f5fa9;padding-bottom:.4rem}
            h2{font-size:1.25rem;margin-top:2.2rem;border-bottom:1px solid #d7dbe0;padding-bottom:.3rem}
            h3{font-size:1.05rem;margin-top:1.6rem;color:#1f5fa9}
            table{border-collapse:collapse;width:100%;margin:.6rem 0 1.2rem}
            th,td{border:1px solid #d7dbe0;padding:.35rem .6rem;text-align:left;vertical-align:top}
            th{background:#f2f4f7;font-size:.86rem;text-transform:uppercase;letter-spacing:.04em}
            code{background:#f2f4f7;padding:.1rem .3rem;border-radius:3px;font-size:.9em}
            li{margin:.1rem 0}
            em{color:#6b7280}
            hr{border:0;border-top:1px solid #d7dbe0;margin:2rem 0}
            </style></head><body>\(body)</body></html>
            """
    }

    // MARK: - Markdown helpers

    /// JavaScript's `a || b` for strings.
    private static func or(_ a: String, _ b: String) -> String { a.isEmpty ? b : a }

    /// `md(s)`: a value made safe for a table cell — pipes escaped, runs of
    /// line feeds (only U+000A, as `/\n+/`) folded to one space, then trimmed.
    private static func md(_ s: String) -> String {
        var out = String.UnicodeScalarView()
        var inBreak = false
        for u in s.unicodeScalars {
            if u == "\n" {
                if !inBreak { out.append(" ") }
                inBreak = true
                continue
            }
            inBreak = false
            if u == "|" { out.append("\\") }
            out.append(u)
        }
        return jsTrim(String(out))
    }

    /// `endDesc(dg, e)`.
    private static func endDesc(_ dg: Diagram, _ e: Endpoint) -> String {
        if e.kind == .boundary { return "boundary \(e.side.rawValue)" }
        guard let b = dg.findBox(e.boxId) else { return "missing box" }
        return "box \(b.number) \(e.side.rawValue)"
    }

    // MARK: - markdownToHtml

    private typealias Scalars = [Unicode.Scalar]

    /// `markdownToHtml(mdText)`: just enough Markdown for the report above. It
    /// works line by line. Every marker its regular expressions look for is
    /// ASCII and all of `\s` is in the BMP, so they are matched here on Unicode
    /// scalars; only `slice(1, -1)` needs code units.
    private static func markdownToHtml(_ mdText: String) -> String {
        var out: [String] = []
        var inTable = false, headerDone = false

        func closeTable() {
            if inTable { out.append("</tbody></table>"); inTable = false; headerDone = false }
        }

        for raw in split(Array(mdText.unicodeScalars), on: "\n") {
            let line = trimEnd(raw)
            if line.first == "|" {
                let cells = split(innerCodeUnits(line), onUnescaped: "|").map { jsTrim(string($0)) }
                if line.allSatisfy({ isJSWhitespace($0) || $0 == "|" || $0 == ":" || $0 == "-" }) { continue }
                if !inTable { out.append("<table><thead>"); inTable = true; headerDone = false }
                if !headerDone {
                    out.append("<tr>\(cells.map { "<th>\(inline($0))</th>" }.joined())</tr></thead><tbody>")
                    headerDone = true
                } else {
                    out.append("<tr>\(cells.map { "<td>\(inline($0))</td>" }.joined())</tr>")
                }
                continue
            }
            closeTable()
            if hasPrefix(line, "### ") {
                out.append("<h3>\(inline(string(line.dropFirst(4))))</h3>")
            } else if hasPrefix(line, "## ") {
                out.append("<h2>\(inline(string(line.dropFirst(3))))</h2>")
            } else if hasPrefix(line, "# ") {
                out.append("<h1>\(inline(string(line.dropFirst(2))))</h1>")
            } else if line == Array("---".unicodeScalars) {
                out.append("<hr>")
            } else if let bullet = bulletItem(line) {
                // JavaScript's whitespace is all in the BMP, so scalars count as code units.
                let indent = Double(bullet.indent) / 2
                out.append("<div style=\"margin-left:\(jsNumberString(indent * 1.4))rem\">• \(inline(string(bullet.text)))</div>")
            } else if !jsTrim(string(line)).isEmpty {
                out.append("<p>\(inline(string(line)))</p>")
            }
        }
        closeTable()
        return out.joined(separator: "\n")
    }

    /// `inline(s)`: escape, then code spans, bold and italics, then `\|` back to `|`.
    private static func inline(_ s: String) -> String {
        var t = Array(escapeXml(s).unicodeScalars)
        t = wrapDelimited(t, "`", count: 1, tag: "code")
        t = wrapDelimited(t, "*", count: 2, tag: "strong")
        t = wrapDelimited(t, "_", count: 1, tag: "em")
        var out = String.UnicodeScalarView()
        var i = 0
        while i < t.count {
            if t[i] == "\\", i + 1 < t.count, t[i + 1] == "|" {
                out.append("|")
                i += 2
            } else {
                out.append(t[i])
                i += 1
            }
        }
        return String(out)
    }

    /// ``.replace(/`([^`]+)`/g, '<code>$1</code>')`` and its `**` and `_`
    /// siblings, for a delimiter of `count` copies of `d`. The class excludes
    /// the delimiter, so the run up to the next `d` is the only candidate at
    /// each start; on failure the scan moves on one scalar, as the regex does.
    private static func wrapDelimited(_ s: Scalars, _ d: Unicode.Scalar, count: Int, tag: String) -> Scalars {
        func delimiterAt(_ i: Int) -> Bool {
            i + count <= s.count && s[i..<(i + count)].allSatisfy { $0 == d }
        }
        var out: Scalars = []
        var i = 0
        while i < s.count {
            if delimiterAt(i) {
                var k = i + count
                while k < s.count, s[k] != d { k += 1 }
                if k > i + count, delimiterAt(k) {
                    out += "<\(tag)>".unicodeScalars
                    out += s[(i + count)..<k]
                    out += "</\(tag)>".unicodeScalars
                    i = k + count
                    continue
                }
            }
            out.append(s[i])
            i += 1
        }
        return out
    }

    /// `line.match(/^(\s*)- /)`: the indent width and the text after the marker.
    private static func bulletItem(_ line: Scalars) -> (indent: Int, text: ArraySlice<Unicode.Scalar>)? {
        var w = 0
        while w < line.count, isJSWhitespace(line[w]) { w += 1 }
        guard w + 1 < line.count, line[w] == "-", line[w + 1] == " " else { return nil }
        return (w, line[(w + 2)...])
    }

    /// `line.slice(1, -1)`, by UTF-16 code units. When the line ends in a
    /// supplementary character the web app keeps its high surrogate, which a
    /// saved file encodes as U+FFFD; decoding the code units repairs it the same way.
    private static func innerCodeUnits(_ line: Scalars) -> Scalars {
        let units = Array(string(line[...]).utf16)
        guard units.count > 2 else { return [] }
        return Array(String(decoding: units[1..<(units.count - 1)], as: UTF16.self).unicodeScalars)
    }

    /// `s.split(sep)` for a one-scalar separator, keeping empty pieces.
    private static func split(_ s: Scalars, on sep: Unicode.Scalar) -> [ArraySlice<Unicode.Scalar>] {
        s.split(separator: sep, omittingEmptySubsequences: false)
    }

    /// `s.split(/(?<!\\)\|/)`: at every separator not directly after a backslash.
    private static func split(_ s: Scalars, onUnescaped sep: Unicode.Scalar) -> [ArraySlice<Unicode.Scalar>] {
        var pieces: [ArraySlice<Unicode.Scalar>] = []
        var start = 0
        for i in s.indices where s[i] == sep && (i == 0 || s[i - 1] != "\\") {
            pieces.append(s[start..<i])
            start = i + 1
        }
        pieces.append(s[start...])
        return pieces
    }

    /// `String.prototype.trimEnd`.
    private static func trimEnd(_ s: ArraySlice<Unicode.Scalar>) -> Scalars {
        var hi = s.endIndex
        while hi > s.startIndex, isJSWhitespace(s[hi - 1]) { hi -= 1 }
        return Array(s[s.startIndex..<hi])
    }

    private static func hasPrefix(_ s: Scalars, _ prefix: String) -> Bool {
        let p = Array(prefix.unicodeScalars)
        return s.count >= p.count && s[0..<p.count].elementsEqual(p)
    }

    private static func string<S: Sequence>(_ s: S) -> String where S.Element == Unicode.Scalar {
        var v = String.UnicodeScalarView()
        v.append(contentsOf: s)
        return String(v)
    }

    private static func string(_ s: Scalars) -> String { string(s[...]) }
}
