// GENERATED by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit by hand.

import SwiftUI

/// Toolkit UI theme for SwiftUI apps. Mirrors css/tokens.css one-to-one.
public enum SCRace: String, CaseIterable, Identifiable {
    case steel
    case crystal
    case chitin
    public var id: String { rawValue }
    public var label: String {
        switch self {
        case .steel: return "Steel"
        case .crystal: return "Crystal"
        case .chitin: return "Chitin"
        }
    }
    public var palette: SCPalette {
        switch self {
        case .steel: return .steel
        case .crystal: return .crystal
        case .chitin: return .chitin
        }
    }
}

public struct SCPalette {
    public let void: Color
    public let bg: Color
    public let panel: Color
    public let panel2: Color
    public let raised: Color
    public let sunken: Color
    public let line: Color
    public let lineStrong: Color
    public let text: Color
    public let text2: Color
    public let text3: Color
    public let accent: Color
    public let accent2: Color
    public let accentInk: Color
    public let glow: Color

    public static let steel = SCPalette(
        void: Color(red: 0.012, green: 0.024, blue: 0.039),
        bg: Color(red: 0.024, green: 0.043, blue: 0.067),
        panel: Color(red: 0.047, green: 0.078, blue: 0.110),
        panel2: Color(red: 0.067, green: 0.110, blue: 0.153),
        raised: Color(red: 0.086, green: 0.137, blue: 0.184),
        sunken: Color(red: 0.016, green: 0.031, blue: 0.051),
        line: Color(red: 0.114, green: 0.204, blue: 0.275),
        lineStrong: Color(red: 0.184, green: 0.357, blue: 0.471),
        text: Color(red: 0.839, green: 0.902, blue: 0.941),
        text2: Color(red: 0.557, green: 0.651, blue: 0.714),
        text3: Color(red: 0.337, green: 0.439, blue: 0.498),
        accent: Color(red: 0.247, green: 0.714, blue: 1.000),
        accent2: Color(red: 1.000, green: 0.702, blue: 0.278),
        accentInk: Color(red: 0.008, green: 0.071, blue: 0.114),
        glow: Color(red: 0.247, green: 0.714, blue: 1.000)
    )
    public static let crystal = SCPalette(
        void: Color(red: 0.008, green: 0.020, blue: 0.047),
        bg: Color(red: 0.020, green: 0.039, blue: 0.094),
        panel: Color(red: 0.039, green: 0.071, blue: 0.149),
        panel2: Color(red: 0.059, green: 0.102, blue: 0.200),
        raised: Color(red: 0.078, green: 0.129, blue: 0.251),
        sunken: Color(red: 0.012, green: 0.027, blue: 0.075),
        line: Color(red: 0.110, green: 0.184, blue: 0.341),
        lineStrong: Color(red: 0.227, green: 0.353, blue: 0.561),
        text: Color(red: 0.875, green: 0.914, blue: 1.000),
        text2: Color(red: 0.580, green: 0.651, blue: 0.784),
        text3: Color(red: 0.353, green: 0.424, blue: 0.565),
        accent: Color(red: 0.208, green: 0.878, blue: 1.000),
        accent2: Color(red: 0.949, green: 0.757, blue: 0.306),
        accentInk: Color(red: 0.008, green: 0.086, blue: 0.125),
        glow: Color(red: 0.208, green: 0.878, blue: 1.000)
    )
    public static let chitin = SCPalette(
        void: Color(red: 0.024, green: 0.012, blue: 0.031),
        bg: Color(red: 0.047, green: 0.024, blue: 0.063),
        panel: Color(red: 0.086, green: 0.047, blue: 0.102),
        panel2: Color(red: 0.118, green: 0.063, blue: 0.141),
        raised: Color(red: 0.157, green: 0.082, blue: 0.184),
        sunken: Color(red: 0.027, green: 0.012, blue: 0.035),
        line: Color(red: 0.227, green: 0.122, blue: 0.251),
        lineStrong: Color(red: 0.416, green: 0.204, blue: 0.455),
        text: Color(red: 0.941, green: 0.878, blue: 0.949),
        text2: Color(red: 0.710, green: 0.588, blue: 0.729),
        text3: Color(red: 0.478, green: 0.365, blue: 0.502),
        accent: Color(red: 0.753, green: 0.357, blue: 1.000),
        accent2: Color(red: 1.000, green: 0.478, blue: 0.102),
        accentInk: Color(red: 0.090, green: 0.012, blue: 0.125),
        glow: Color(red: 0.753, green: 0.357, blue: 1.000)
    )
}

public enum SCStatus {
    public static let danger = Color(red: 1.000, green: 0.302, blue: 0.369)
    public static let warning = Color(red: 1.000, green: 0.690, blue: 0.125)
    public static let success = Color(red: 0.243, green: 0.878, blue: 0.478)
    public static let info = Color(red: 0.310, green: 0.765, blue: 1.000)
}

public enum SCAppColor {
    public static let heptabase = Color(red: 0.643, green: 0.553, blue: 0.941)
    public static let idef0 = Color(red: 0.416, green: 0.659, blue: 0.902)
    public static let pyramid = Color(red: 0.878, green: 0.604, blue: 0.353)
    public static let metropolis = Color(red: 0.235, green: 0.733, blue: 0.655)
}

/// Font helpers. Bundle the TTF/OTF files of these families in the app target
/// (Google Fonts, OFL); the woff2 files in fonts/ are for the web only.
public enum SCFont {
    public static func display(_ size: CGFloat, weight: Font.Weight = .regular) -> Font {
        Font.custom("Orbitron", size: size).weight(weight)
    }
    public static func ui(_ size: CGFloat, weight: Font.Weight = .regular) -> Font {
        Font.custom("Exo 2", size: size).weight(weight)
    }
    public static func mono(_ size: CGFloat, weight: Font.Weight = .regular) -> Font {
        Font.custom("Share Tech Mono", size: size).weight(weight)
    }
}
