// Report.swift against the web app: the sample's Markdown report
// (golden-exports.json), the report of every scenario assembled from that
// scenario's golden record, the HTML converter's structure on the sample, and
// two hand-built models whose reports exercise what the sample never reaches.
//
// There is no HTML golden. The sample's HTML is checked for what reading
// markdownToHtml in src/io/report.js implies — headings, table rows, inline
// markup, escaping — and the two hand-built models were rendered by
// src/io/report.js itself (`deserialize`, `bindAll` where noted, `toMarkdown`,
// `toHtml`) in Node 26.8.2, the date line masked to DATE; those expectations
// are the web app's output verbatim.

import Foundation
import Testing
@testable import IDEF0Core

@Suite("ReportParity")
struct ReportParityTests {

    // MARK: Helpers

    private static let exports = Fixtures.json("golden-exports.json").objectValue!
    private static let scenarios = Fixtures.json("golden-scenarios.json").objectValue!

    private static func sample() throws -> IDEF0Model {
        var m = try ModelFile.deserialize(Fixtures.sampleText)
        m.bindAll()
        return m
    }

    /// `md(s)` from report.js: `String(s ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim()`.
    private static func md(_ s: String) -> String {
        var out = ""
        var lastWasBreak = false
        for u in s.unicodeScalars {
            if u == "\n" {
                if !lastWasBreak { out.unicodeScalars.append(" ") }
                lastWasBreak = true
                continue
            }
            lastWasBreak = false
            if u == "|" { out.unicodeScalars.append("\\") }
            out.unicodeScalars.append(u)
        }
        return jsTrim(out)
    }

    private static func or(_ a: String, _ b: String) -> String { a.isEmpty ? b : a }

    /// Text equal to the code unit, which Swift's `==` (canonical equivalence) is not.
    private static func sameBytes(_ a: String, _ b: String) -> Bool { a.utf8.elementsEqual(b.utf8) }

    private static func lines(_ s: String) -> [String] { s.components(separatedBy: "\n") }

    /// The page's body, one converter output per line.
    private static func bodyLines(_ html: String) throws -> [String] {
        let start = try #require(html.range(of: "</style></head><body>"))
        #expect(html.hasSuffix("</body></html>"))
        return lines(String(html[start.upperBound...].dropLast("</body></html>".count)))
    }

    // MARK: Goldens

    @Test("the sample's Markdown report matches the web app's to the byte")
    func sampleMarkdown() throws {
        let golden = try #require(Self.exports["markdown"]?.stringValue)
        let actual = Report.markdown(try Self.sample(), generatedOn: "DATE")
        #expect(textDiff(golden, actual) == nil, "\(textDiff(golden, actual) ?? "")")
        #expect(Self.sameBytes(golden, actual))
    }

    @Test("only the closing line carries the date")
    func generatedOn() throws {
        let m = try Self.sample()
        let a = Self.lines(Report.markdown(m, generatedOn: "2026-01-02"))
        let b = Self.lines(Report.markdown(m, generatedOn: "1999-12-31"))
        #expect(a.dropLast() == b.dropLast())
        #expect(a.last == "_Generated by IDEF0 Modeler on 2026-01-02._")
        #expect(b.last == "_Generated by IDEF0 Modeler on 1999-12-31._")
    }

    @Test("every golden issue of a scenario is a row of its Rule check table", arguments: ScenarioReplayer.names)
    func ruleCheckRows(_ name: String) throws {
        let golden = try #require(Self.scenarios[name]?.objectValue)
        let nodes = Dictionary(
            (golden["diagrams"]?.arrayValue ?? []).compactMap { d -> (String, String)? in
                guard let o = d.objectValue, let id = o["id"]?.stringValue, let node = o["node"]?.stringValue else { return nil }
                return (id, node)
            },
            uniquingKeysWith: { first, _ in first })
        let report = Report.markdown(try ScenarioReplayer.model(for: name), generatedOn: "DATE")
        let all = Self.lines(report)
        let start = try #require(all.lastIndex(of: "## Rule check"), "\(name): no Rule check section")
        let table = Array(all[start...])

        let issues = try #require(golden["issues"]?.arrayValue)
        for row in issues {
            let r = try #require(row.arrayValue)
            let severity = r[0].stringValue!, code = r[1].stringValue!, message = r[2].stringValue!
            #expect(table.contains { $0.contains(Self.md(message)) }, "\(name): no row carries “\(message)”")
            let node = Self.or(r[3].stringValue.flatMap { nodes[$0] } ?? "", "—")
            let line = "| \(severity) | \(node) | `\(code)` | \(Self.md(message)) |"
            #expect(table.contains { Self.sameBytes($0, line) }, "\(name): missing row \(line)")
        }
    }

    @Test("every scenario's report is the one its golden record describes", arguments: ScenarioReplayer.names)
    func scenarioReport(_ name: String) throws {
        let golden = try #require(Self.scenarios[name]?.objectValue)
        let expected = try Self.expectedReport(golden)
        let actual = Report.markdown(try ScenarioReplayer.model(for: name), generatedOn: "DATE")
        #expect(textDiff(expected, actual) == nil, "\(name): \(textDiff(expected, actual) ?? "")")
        #expect(Self.sameBytes(expected, actual), "\(name): the texts differ in their code units")
    }

    /// toMarkdown's layout filled from a scenario's golden record alone: the
    /// saved file for the text, the tree for the order, and the web app's own
    /// sortedBoxes, ICOM codes, roles, concept queries and issues.
    private static func expectedReport(_ g: JSONObject) throws -> String {
        let roleLabel = ["input": "Input", "control": "Control", "output": "Output",
                         "mechanism": "Mechanism", "call": "Call", "unknown": "Unclassified"]
        let fileText = try #require(g["file"]?.stringValue)
        let file = try #require(try JSONValue.parse(fileText).objectValue)
        let fileDiagrams = try #require(file["diagrams"]?.objectValue)
        var goldenDiagrams: [String: JSONObject] = [:]
        for d in g["diagrams"]?.arrayValue ?? [] {
            if let o = d.objectValue, let id = o["id"]?.stringValue { goldenDiagrams[id] = o }
        }
        func str(_ v: JSONValue?) -> String { v?.stringValue ?? "" }
        func int(_ v: JSONValue?) -> Int {
            if case .number(let n)? = v { return Int(n) }
            return 0
        }
        func objects(_ v: JSONValue?) -> [JSONObject] { (v?.arrayValue ?? []).compactMap(\.objectValue) }
        /// Box positions in the order a golden's `sortedBoxes` names them. Ids
        /// can repeat in a model that duplicates one, so each is taken once.
        func sortedOrder(_ gd: JSONObject) -> [Int] {
            let boxes = objects(gd["boxes"])
            var taken = Set<Int>()
            var out: [Int] = []
            for id in (gd["sortedBoxes"]?.arrayValue ?? []).compactMap(\.stringValue) {
                guard let k = boxes.indices.first(where: { !taken.contains($0) && str(boxes[$0]["id"]) == id }) else { continue }
                taken.insert(k)
                out.append(k)
            }
            return out
        }

        let title = str(file["title"])
        var L: [String] = []
        L += ["# \(or(title, "Untitled IDEF0 Model"))", ""]
        L += ["| | |", "|---|---|"]
        for (label, key) in [("Author", "author"), ("Project", "project"), ("Status", "status"), ("Created", "created"), ("Revised", "revised")] {
            L.append("| \(label) | \(md(str(file[key]))) |")
        }
        L.append("")
        L += ["**Purpose.** " + or(jsTrim(str(file["purpose"])), "_not stated_"), ""]
        L += ["**Viewpoint.** " + or(jsTrim(str(file["viewpoint"])), "_not stated_"), ""]

        let tree = (g["tree"]?.arrayValue ?? []).compactMap { $0.arrayValue?.first?.stringValue }
        L += ["## Node index", ""]
        // Every box is listed; a detail diagram already on the path (a
        // decomposition cycle) is not entered again.
        var path = Set<String>()
        func walk(_ id: String, _ depth: Int) {
            guard let gd = goldenDiagrams[id] else { return }
            path.insert(id)
            defer { path.remove(id) }
            let boxes = objects(gd["boxes"])
            for b in sortedOrder(gd).map({ boxes[$0] }) {
                L.append("\(String(repeating: "  ", count: depth))- **\(str(b["node"]))** \(or(str(b["name"]), "_(unnamed)_"))")
                let child = str(b["childDiagramId"])
                if !child.isEmpty, goldenDiagrams[child] != nil, !path.contains(child) { walk(child, depth + 1) }
            }
        }
        if let root = tree.first { walk(root, 0) }
        L.append("")

        L += ["## Diagrams", ""]
        for id in tree {
            let gd = try #require(goldenDiagrams[id]), fd = try #require(fileDiagrams[id]?.objectValue)
            L += ["### \(str(gd["node"])) — \(or(str(gd["title"]), title))", ""]
            if !str(fd["cNumber"]).isEmpty { L += ["C-number: `\(str(fd["cNumber"]))`", ""] }

            let goldenBoxes = objects(gd["boxes"]), fileBoxes = objects(fd["boxes"])
            let sorted = sortedOrder(gd)
            L += ["**Activities**", ""]
            L += ["| Box | Node | Name | Decomposed |", "|---|---|---|---|"]
            for b in sorted.map({ goldenBoxes[$0] }) {
                // "yes" only when the link names a diagram the model holds.
                let decomposed = goldenDiagrams[str(b["childDiagramId"])] == nil ? "no" : "yes"
                L.append("| \(int(b["number"])) | \(str(b["node"])) | \(or(md(str(b["name"])), "_(unnamed)_")) | \(decomposed) |")
            }
            L.append("")

            var codes: [String: String] = [:]
            for row in gd["icom"]?.arrayValue ?? [] {
                guard let r = row.arrayValue, let code = r[2].stringValue else { continue }
                codes["\(str(r[0])):\(str(r[1]))"] = code
            }
            func endDesc(_ e: JSONObject) -> String {
                if str(e["type"]) == "boundary" { return "boundary \(str(e["side"]))" }
                guard let b = fileBoxes.first(where: { str($0["id"]) == str(e["boxId"]) }) else { return "missing box" }
                return "box \(int(b["number"])) \(str(e["side"]))"
            }
            L += ["**Arrows**", ""]
            L += ["| Role | Label | From | To | ICOM | Tunnel |", "|---|---|---|---|---|---|"]
            let goldenArrows = objects(gd["arrows"])
            for (k, a) in objects(fd["arrows"]).enumerated() {
                let role = try #require(roleLabel[str(goldenArrows[k]["role"])])
                let code = or(codes["\(str(a["id"])):from"] ?? "", codes["\(str(a["id"])):to"] ?? "")
                let tunnel = a["tunnelFrom"] == .bool(true) || a["tunnelTo"] == .bool(true) ? "yes" : ""
                let from = endDesc(try #require(a["from"]?.objectValue)), to = endDesc(try #require(a["to"]?.objectValue))
                L.append("| \(role) | \(or(md(str(a["label"])), "_(unlabelled)_")) | \(from) | \(to) | \(code) | \(tunnel) |")
            }
            L.append("")

            let notes = sorted.filter { !jsTrim(str(fileBoxes[$0]["note"])).isEmpty }
            if !notes.isEmpty {
                L += ["**Notes**", ""]
                for k in notes {
                    let node = str(goldenBoxes[k]["node"])
                    L.append("- **\(node)** — \(md(str(fileBoxes[k]["note"])))")
                }
                L.append("")
            }
        }

        let concepts = try #require(g["concepts"]?.objectValue)
        let glossary = (concepts["glossary"]?.arrayValue ?? []).compactMap(\.arrayValue)
        if !glossary.isEmpty {
            let usage = (concepts["usage"]?.arrayValue ?? []).compactMap(\.arrayValue)
            let occurrences = (concepts["occurrences"]?.arrayValue ?? []).compactMap(\.arrayValue)
            L += ["## Concepts", ""]
            L += ["| Term | Kind | Used | Occurs on | Definition |", "|---|---|---|---|---|"]
            for (k, c) in glossary.enumerated() {
                let whereUsed = objects(occurrences[k][1])
                    .map { "\(str($0["node"]))\u{00A0}\(str($0["kind"]) == "box" ? "act" : "obj")" }
                    .joined(separator: ", ")
                L.append("| \(md(str(c[1]))) | \(str(c[2])) | \(int(usage[k][1])) | \(or(whereUsed, "—")) | \(or(md(str(c[3])), "_undefined_")) |")
            }
            L.append("")

            let drift = objects(concepts["drift"])
            if !drift.isEmpty {
                L += ["### Label elaboration", ""]
                L += ["Places where the drawn text differs from the concept it denotes — legitimate under FIPS 183 §3.3.2.4.", ""]
                L += ["| Where | Reads | Concept |", "|---|---|---|"]
                for d in drift {
                    L.append("| \(str(d["node"])) \(str(d["kind"]) == "box" ? "activity" : "arrow") | \(md(str(d["text"]))) | \(md(str(d["term"]))) |")
                }
                L.append("")
            }

            let unused = (concepts["unused"]?.arrayValue ?? []).compactMap(\.stringValue)
            if !unused.isEmpty {
                let terms = unused.map { id in md(str(glossary.first { str($0[0]) == id }?[1])) }
                L += ["_\(unused.count) concept(s) defined but not used: \(terms.joined(separator: ", "))._", ""]
            }
        }

        let summary = try #require(g["summary"]?.objectValue)
        let issues = (g["issues"]?.arrayValue ?? []).compactMap(\.arrayValue)
        L += ["## Rule check", ""]
        L += ["\(int(summary["errors"])) error(s), \(int(summary["warnings"])) warning(s).", ""]
        if !issues.isEmpty {
            L += ["| Severity | Diagram | Rule | Detail |", "|---|---|---|---|"]
            for i in issues {
                let node = or(i[3].stringValue.flatMap { goldenDiagrams[$0].map { str($0["node"]) } } ?? "", "—")
                L.append("| \(str(i[0])) | \(node) | `\(str(i[1]))` | \(md(str(i[2]))) |")
            }
            L.append("")
        }
        L += ["---", "", "_Generated by IDEF0 Modeler on DATE._"]
        return L.joined(separator: "\n")
    }

    // MARK: HTML structure (sample)

    @Test("the HTML page wraps the converted report in the web app's head")
    func htmlDocument() throws {
        let html = Report.html(try Self.sample(), generatedOn: "2026-01-02")
        #expect(html.hasPrefix(
            "<!doctype html><html><head><meta charset=\"utf-8\"><title>Manufacture Product — IDEF0 report</title>\n<style>\nbody{font:14px/1.6 -apple-system,"))
        #expect(html.contains("\n  max-width:60rem;margin:2.5rem auto;padding:0 1.5rem;color:#1c2024}\nh1{"))
        #expect(html.contains("hr{border:0;border-top:1px solid #d7dbe0;margin:2rem 0}\n</style></head><body><h1>Manufacture Product</h1>\n"))
        #expect(html.hasSuffix("\n<hr>\n<p><em>Generated by IDEF0 Modeler on 2026-01-02.</em></p></body></html>"))
    }

    @Test("markdownToHtml turns the sample's headings, lists and paragraphs into their elements")
    func htmlBlocks() throws {
        let m = try Self.sample()
        let body = try Self.bodyLines(Report.html(m, generatedOn: "2026-01-02"))
        let markdown = Self.lines(Report.markdown(m, generatedOn: "2026-01-02"))

        #expect(body.first == "<h1>Manufacture Product</h1>")
        #expect(body.contains("<p><strong>Purpose.</strong> \(m.purpose)</p>"))
        #expect(body.contains("<p><strong>Viewpoint.</strong> \(m.viewpoint)</p>"))
        #expect(body.contains("<h2>Node index</h2>"))
        #expect(body.contains("<div style=\"margin-left:0rem\">• <strong>A0</strong> Manufacture Product</div>"))
        #expect(body.contains("<div style=\"margin-left:1.4rem\">• <strong>A1</strong> Plan Production</div>"))
        #expect(body.contains("<h3>A-0 — Manufacture Product</h3>"))
        #expect(body.contains("<p><strong>Activities</strong></p>"))
        #expect(body.contains("<p>0 error(s), 12 warning(s).</p>"))

        // One element per non-blank Markdown line; blank lines emit nothing.
        #expect(!body.contains(""))
        #expect(body.filter { $0.hasPrefix("<h1>") }.count == markdown.filter { $0.hasPrefix("# ") }.count)
        #expect(body.filter { $0.hasPrefix("<h2>") }.count == markdown.filter { $0.hasPrefix("## ") }.count)
        #expect(body.filter { $0.hasPrefix("<h3>") }.count == markdown.filter { $0.hasPrefix("### ") }.count)
        #expect(body.filter { $0.hasPrefix("<div style=") }.count == markdown.filter { $0.hasPrefix("- ") || $0.hasPrefix("  - ") }.count)
        #expect(body.filter { $0 == "<hr>" }.count == 1)
        #expect(!body.contains { $0.hasPrefix("|") || $0.hasPrefix("#") || $0.contains("**") || $0.contains("`") })
    }

    @Test("markdownToHtml turns the sample's tables into rows, header row first")
    func htmlTables() throws {
        let m = try Self.sample()
        let body = try Self.bodyLines(Report.html(m, generatedOn: "2026-01-02"))
        let markdown = Self.lines(Report.markdown(m, generatedOn: "2026-01-02"))
        let separator: (String) -> Bool = { line in
            line.unicodeScalars.allSatisfy { isJSWhitespace($0) || $0 == "|" || $0 == ":" || $0 == "-" }
        }
        let tableLines = markdown.filter { $0.hasPrefix("|") }
        let rows = tableLines.filter { !separator($0) }

        // `| | |` passes the separator test, so the header-field table's first row is Author.
        #expect(Array(body[1...7]) == [
            "<table><thead>",
            "<tr><th>Author</th><th>A. Modeller</th></tr></thead><tbody>",
            "<tr><td>Project</td><td>Plant Operations Baseline</td></tr>",
            "<tr><td>Status</td><td>DRAFT</td></tr>",
            "<tr><td>Created</td><td>2026-09-14</td></tr>",
            "<tr><td>Revised</td><td>2026-09-14</td></tr>",
            "</tbody></table>",
        ])
        let opens = body.indices.filter { body[$0] == "<table><thead>" }
        #expect(opens.count == 7)
        #expect(body.filter { $0 == "</tbody></table>" }.count == opens.count)
        for i in opens { #expect(body[i + 1].hasPrefix("<tr><th>") && body[i + 1].hasSuffix("</tr></thead><tbody>")) }
        #expect(body.filter { $0.hasPrefix("<tr>") }.count == rows.count)

        #expect(body.contains("<tr><th>Role</th><th>Label</th><th>From</th><th>To</th><th>ICOM</th><th>Tunnel</th></tr></thead><tbody>"))
        #expect(body.contains("<tr><td>Input</td><td>Customer Order</td><td>boundary left</td><td>box 0 left</td><td></td><td></td></tr>"))
        #expect(body.contains("<tr><td>Output</td><td>Shipping Notice</td><td>box 4 right</td><td>boundary right</td><td>O2</td><td></td></tr>"))
        #expect(body.contains("<tr><td>Assemble Product</td><td>activity</td><td>1</td><td>A3\u{00A0}act</td><td><em>undefined</em></td></tr>"))
        #expect(body.contains(
            "<tr><td>warning</td><td>A0</td><td><code>concept-undefined</code></td><td>“Assemble Product” (activity) is used 1× but has no glossary definition.</td></tr>"))
    }

    @Test("markdownToHtml escapes markup, then applies code, bold, italics and escaped pipes")
    func htmlEscaping() throws {
        var m = try Self.sample()
        m.title = "<Plant> & \"Co\" it's"
        let a0 = try #require(m.diagrams.keys.last)
        m.updateDiagram(a0) { dg in
            dg.arrows[0].label = "Plan | Actual"
            dg.arrows[1].label = "a_b_c `x<y` **bold**"
        }
        let html = Report.html(m, generatedOn: "2026-01-02")
        let body = try Self.bodyLines(html)
        #expect(html.contains("<title>&lt;Plant&gt; &amp; &quot;Co&quot; it&apos;s — IDEF0 report</title>"))
        #expect(body.first == "<h1>&lt;Plant&gt; &amp; &quot;Co&quot; it&apos;s</h1>")
        #expect(body.contains("<tr><td>Input</td><td>Plan | Actual</td><td>boundary left</td><td>box 1 left</td><td>I1</td><td></td></tr>"))
        #expect(body.contains { $0.hasPrefix("<tr><td>Input</td><td>a<em>b</em>c <code>x&lt;y</code> <strong>bold</strong></td>") })
    }

    // MARK: Captured from the web app

    /// Every report feature the sample lacks: escaping in each field, an
    /// untitled diagram, a C-number, notes with pipes and CR LF, an unnamed box,
    /// out-of-order box numbers, a tunnel, a dangling end, drift, an unused
    /// concept, NFC and NFD spellings of one term, and list and heading
    /// look-alikes in the purpose. Deserialized, then `bindAll`.
    private static let edgeFile = ##"{"title": "Caf\u00e9 <Plant> & \"Co\" | *x* _y_ `z` it's", "author": "a|b\n\nc  ", "project": "", "status": "", "created": "2026-01-02", "revised": "", "purpose": "  Line one\n - half indent\n   - one and a half\n### not a table | x\n---\n\n#### four\n**bold** and ***three***x** and __ and _a_b_ `c`d` \u00a0\n  ", "viewpoint": "\u3000", "glossary": [{"id": "g1", "term": "Order", "kind": "data", "definition": "Has a | pipe and \\| escaped"}, {"id": "g2", "term": "Unused | term", "kind": "other", "definition": "**Bold** def with `code` and a_b_c\nline two"}], "diagrams": {"d0": {"id": "d0", "node": "A-0", "title": "", "boxes": [{"id": "b0", "name": "Run Plant", "number": 0, "childDiagramId": "d1"}], "arrows": [{"id": "a0", "label": "Order", "conceptId": "g1", "from": {"type": "boundary", "side": "left", "pos": 0.5}, "to": {"type": "box", "boxId": "b0", "side": "left", "pos": 0.5}}, {"id": "a0b", "label": "Plan | Actual", "from": {"type": "boundary", "side": "top", "pos": 0.5}, "to": {"type": "box", "boxId": "b0", "side": "top", "pos": 0.5}}]}, "d1": {"id": "d1", "node": "A0", "title": "", "cNumber": "AM-12", "parentBoxId": "b0", "boxes": [{"id": "b1", "name": "", "number": 2, "x": 400, "y": 300, "note": "Needs **review** | see _spec_\n\nsecond line\r\nthird"}, {"id": "b2", "name": "Ship \\| *Product* __x__", "number": 1, "note": "   "}], "arrows": [{"id": "a1", "label": "Order Records", "conceptId": "g1", "from": {"type": "boundary", "side": "left", "pos": 0.5}, "to": {"type": "box", "boxId": "b2", "side": "left", "pos": 0.5}, "tunnelFrom": true}, {"id": "a2", "label": "Plan \\| Actual * `code` _it_ <&>", "from": {"type": "boundary", "side": "top", "pos": 0.5}, "to": {"type": "box", "boxId": "b1", "side": "top", "pos": 0.5}}, {"id": "a3", "label": "", "from": {"type": "box", "boxId": "b2", "side": "right", "pos": 0.5}, "to": {"type": "box", "boxId": "bx_gone", "side": "left", "pos": 0.5}}, {"id": "a4", "label": "Cafe\u0301 Menu", "from": {"type": "box", "boxId": "b1", "side": "bottom", "pos": 0.5}, "to": {"type": "boundary", "side": "bottom", "pos": 0.5}}, {"id": "a5", "label": "Caf\u00e9 Menu", "from": {"type": "box", "boxId": "b1", "side": "right", "pos": 0.5}, "to": {"type": "boundary", "side": "right", "pos": 0.5}}]}}, "rootDiagramId": "d0"}"##

    /// The converter's table corner cases, in the purpose: a lone pipe, rows
    /// that are all separators, a trailing unescaped pipe, an escaped pipe, a
    /// cell ending in a supplementary character. Deserialized without `bindAll`.
    private static let quirksFile = ##"{"title": "", "created": "2026-01-02", "revised": "2026-01-03", "purpose": "|\n||\n|x\n|  \n| - |\n\\|x|\n  |x|y|\n| a \\| b | c\\\\|d |\n|\ud83d\ude42\ntext\n|`a|b`|", "viewpoint": "View", "diagrams": {"d0": {"id": "d0", "node": "A-0", "title": "", "boxes": [], "arrows": []}}, "rootDiagramId": "d0"}"##

    @Test("a model exercising every report section renders as the web app renders it")
    func edgeReport() throws {
        var m = try ModelFile.deserialize(Self.edgeFile)
        m.bindAll()
        let markdown = Report.markdown(m, generatedOn: "DATE")
        #expect(textDiff(Self.edgeMarkdown, markdown) == nil, "\(textDiff(Self.edgeMarkdown, markdown) ?? "")")
        #expect(Self.sameBytes(Self.edgeMarkdown, markdown))

        let html = Report.html(m, generatedOn: "DATE")
        #expect(html.hasPrefix(
            "<!doctype html><html><head><meta charset=\"utf-8\"><title>Café &lt;Plant&gt; &amp; &quot;Co&quot; | *x* _y_ `z` it&apos;s — IDEF0 report</title>\n<style>\n"))
        let body = try Self.bodyLines(html).joined(separator: "\n")
        #expect(textDiff(Self.edgeBody, body) == nil, "\(textDiff(Self.edgeBody, body) ?? "")")
        #expect(Self.sameBytes(Self.edgeBody, body))
    }

    @Test("table corner cases convert as the web app converts them")
    func quirksReport() throws {
        let m = try ModelFile.deserialize(Self.quirksFile)
        let markdown = Report.markdown(m, generatedOn: "DATE")
        #expect(textDiff(Self.quirksMarkdown, markdown) == nil, "\(textDiff(Self.quirksMarkdown, markdown) ?? "")")
        #expect(Self.sameBytes(Self.quirksMarkdown, markdown))

        let html = Report.html(m, generatedOn: "DATE")
        #expect(html.hasPrefix("<!doctype html><html><head><meta charset=\"utf-8\"><title> — IDEF0 report</title>\n<style>\n"))
        let body = try Self.bodyLines(html).joined(separator: "\n")
        #expect(textDiff(Self.quirksBody, body) == nil, "\(textDiff(Self.quirksBody, body) ?? "")")
        #expect(Self.sameBytes(Self.quirksBody, body))
    }

    private static let edgeMarkdown = #"""
    # Caf\#u{E9} <Plant> & "Co" | *x* _y_ `z` it's

    | | |
    |---|---|
    | Author | a\|b c |
    | Project |  |
    | Status |  |
    | Created | 2026-01-02 |
    | Revised |  |

    **Purpose.** Line one
     - half indent
       - one and a half
    ### not a table | x
    ---

    #### four
    **bold** and ***three***x** and __ and _a_b_ `c`d`

    **Viewpoint.** _not stated_

    ## Node index

    - **A0** Run Plant
      - **A1** Ship \| *Product* __x__
      - **A2** _(unnamed)_

    ## Diagrams

    ### A-0 — Caf\#u{E9} <Plant> & "Co" | *x* _y_ `z` it's

    **Activities**

    | Box | Node | Name | Decomposed |
    |---|---|---|---|
    | 0 | A0 | Run Plant | yes |

    **Arrows**

    | Role | Label | From | To | ICOM | Tunnel |
    |---|---|---|---|---|---|
    | Input | Order | boundary left | box 0 left |  |  |
    | Control | Plan \| Actual | boundary top | box 0 top |  |  |

    ### A0 — Caf\#u{E9} <Plant> & "Co" | *x* _y_ `z` it's

    C-number: `AM-12`

    **Activities**

    | Box | Node | Name | Decomposed |
    |---|---|---|---|
    | 1 | A1 | Ship \\| *Product* __x__ | no |
    | 2 | A2 | _(unnamed)_ | no |

    **Arrows**

    | Role | Label | From | To | ICOM | Tunnel |
    |---|---|---|---|---|---|
    | Input | Order Records | boundary left | box 1 left |  | yes |
    | Control | Plan \\| Actual * `code` _it_ <&> | boundary top | box 2 top | C1 |  |
    | Input | _(unlabelled)_ | box 1 right | missing box |  |  |
    | Call | Cafe\#u{301} Menu | box 2 bottom | boundary bottom |  |  |
    | Output | Caf\#u{E9} Menu | box 2 right | boundary right |  |  |

    **Notes**

    - **A2** — Needs **review** \| see _spec_ second line\#r third

    ## Concepts

    | Term | Kind | Used | Occurs on | Definition |
    |---|---|---|---|---|
    | Cafe\#u{301} Menu | data | 1 | A0\#u{A0}obj | _undefined_ |
    | Caf\#u{E9} Menu | data | 1 | A0\#u{A0}obj | _undefined_ |
    | Order | data | 2 | A-0\#u{A0}obj, A0\#u{A0}obj | Has a \| pipe and \\| escaped |
    | Plan \\| Actual * `code` _it_ <&> | data | 1 | A0\#u{A0}obj | _undefined_ |
    | Plan \| Actual | data | 1 | A-0\#u{A0}obj | _undefined_ |
    | Run Plant | activity | 1 | A0\#u{A0}act | _undefined_ |
    | Ship \\| *Product* __x__ | activity | 1 | A1\#u{A0}act | _undefined_ |
    | Unused \| term | other | 0 | — | **Bold** def with `code` and a_b_c line two |

    ### Label elaboration

    Places where the drawn text differs from the concept it denotes — legitimate under FIPS 183 §3.3.2.4.

    | Where | Reads | Concept |
    |---|---|---|
    | A0 arrow | Order Records | Order |

    _1 concept(s) defined but not used: Unused \| term._

    ## Rule check

    7 error(s), 10 warning(s).

    | Severity | Diagram | Rule | Detail |
    |---|---|---|---|
    | error | A-0 | `box-output` | A0 has no output. Every IDEF0 box requires at least one output arrow from its right. |
    | error | A0 | `icom-orphan` | A0: boundary output “Caf\#u{E9} Menu” on the right has no matching arrow on parent box A0. Connect it on A-0 or tunnel it. |
    | error | A-0 | `icom-missing` | A-0: I1 “Order” on box A0 (left) does not appear as a boundary arrow on A0. Add it there or tunnel it. |
    | error | A0 | `box-name` | Box 2 on A0 is unnamed. Box names are active verb phrases. |
    | error | A0 | `box-control` | A1 has no control. Every IDEF0 box requires at least one control arrow on its top. |
    | error | A0 | `arrow-label` | An unlabelled input arrow on A0. Arrow labels are noun phrases. |
    | error | A0 | `arrow-dangling` | An arrow on A0 points at a box that no longer exists. |
    | warning | A-0 | `model-viewpoint` | The model states no viewpoint. Every IDEF0 model must declare one. |
    | warning | A0 | `icom-concept-mismatch` | A0: C1 “Plan \\| Actual * `code` _it_ <&>” is bound to a different concept than parent box A0 carries as “Plan \| Actual”. The two ends of an ICOM pair should denote the same object (§3.3.2.4). |
    | warning | A0 | `icom-relabel` | A0: C1 reads “Plan \\| Actual * `code` _it_ <&>” where parent box A0 carries “Plan \| Actual”. Fine if it details that arrow — otherwise the two have drifted apart. |
    | warning | A0 | `decomp-count` | A0 has 2 box(es). A decomposition should have 3–6; fewer than 3 adds no detail. |
    | warning | A0 | `concept-undefined` | “Cafe\#u{301} Menu” (data) is used 1× but has no glossary definition. |
    | warning | A0 | `concept-undefined` | “Caf\#u{E9} Menu” (data) is used 1× but has no glossary definition. |
    | warning | A0 | `concept-undefined` | “Plan \\| Actual * `code` _it_ <&>” (data) is used 1× but has no glossary definition. |
    | warning | A-0 | `concept-undefined` | “Plan \| Actual” (data) is used 1× but has no glossary definition. |
    | warning | A-0 | `concept-undefined` | “Run Plant” (activity) is used 1× but has no glossary definition. |
    | warning | A0 | `concept-undefined` | “Ship \\| *Product* __x__” (activity) is used 1× but has no glossary definition. |

    ---

    _Generated by IDEF0 Modeler on DATE._
    """#

    private static let edgeBody = #"""
    <h1>Caf\#u{E9} &lt;Plant&gt; &amp; &quot;Co&quot; | *x* <em>y</em> <code>z</code> it&apos;s</h1>
    <table><thead>
    <tr><th>Author</th><th>a|b c</th></tr></thead><tbody>
    <tr><td>Project</td><td></td></tr>
    <tr><td>Status</td><td></td></tr>
    <tr><td>Created</td><td>2026-01-02</td></tr>
    <tr><td>Revised</td><td></td></tr>
    </tbody></table>
    <p><strong>Purpose.</strong> Line one</p>
    <div style="margin-left:0.7rem">• half indent</div>
    <div style="margin-left:2.0999999999999996rem">• one and a half</div>
    <h3>not a table | x</h3>
    <hr>
    <p>#### four</p>
    <p><strong>bold</strong> and *<strong>three</strong>*x** and _<em> and </em>a<em>b</em> <code>c</code>d`</p>
    <p><strong>Viewpoint.</strong> <em>not stated</em></p>
    <h2>Node index</h2>
    <div style="margin-left:0rem">• <strong>A0</strong> Run Plant</div>
    <div style="margin-left:1.4rem">• <strong>A1</strong> Ship | *Product* _<em>x</em>_</div>
    <div style="margin-left:1.4rem">• <strong>A2</strong> <em>(unnamed)</em></div>
    <h2>Diagrams</h2>
    <h3>A-0 — Caf\#u{E9} &lt;Plant&gt; &amp; &quot;Co&quot; | *x* <em>y</em> <code>z</code> it&apos;s</h3>
    <p><strong>Activities</strong></p>
    <table><thead>
    <tr><th>Box</th><th>Node</th><th>Name</th><th>Decomposed</th></tr></thead><tbody>
    <tr><td>0</td><td>A0</td><td>Run Plant</td><td>yes</td></tr>
    </tbody></table>
    <p><strong>Arrows</strong></p>
    <table><thead>
    <tr><th>Role</th><th>Label</th><th>From</th><th>To</th><th>ICOM</th><th>Tunnel</th></tr></thead><tbody>
    <tr><td>Input</td><td>Order</td><td>boundary left</td><td>box 0 left</td><td></td><td></td></tr>
    <tr><td>Control</td><td>Plan | Actual</td><td>boundary top</td><td>box 0 top</td><td></td><td></td></tr>
    </tbody></table>
    <h3>A0 — Caf\#u{E9} &lt;Plant&gt; &amp; &quot;Co&quot; | *x* <em>y</em> <code>z</code> it&apos;s</h3>
    <p>C-number: <code>AM-12</code></p>
    <p><strong>Activities</strong></p>
    <table><thead>
    <tr><th>Box</th><th>Node</th><th>Name</th><th>Decomposed</th></tr></thead><tbody>
    <tr><td>1</td><td>A1</td><td>Ship \| *Product* _<em>x</em>_</td><td>no</td></tr>
    <tr><td>2</td><td>A2</td><td><em>(unnamed)</em></td><td>no</td></tr>
    </tbody></table>
    <p><strong>Arrows</strong></p>
    <table><thead>
    <tr><th>Role</th><th>Label</th><th>From</th><th>To</th><th>ICOM</th><th>Tunnel</th></tr></thead><tbody>
    <tr><td>Input</td><td>Order Records</td><td>boundary left</td><td>box 1 left</td><td></td><td>yes</td></tr>
    <tr><td>Control</td><td>Plan \| Actual * <code>code</code> <em>it</em> &lt;&amp;&gt;</td><td>boundary top</td><td>box 2 top</td><td>C1</td><td></td></tr>
    <tr><td>Input</td><td><em>(unlabelled)</em></td><td>box 1 right</td><td>missing box</td><td></td><td></td></tr>
    <tr><td>Call</td><td>Cafe\#u{301} Menu</td><td>box 2 bottom</td><td>boundary bottom</td><td></td><td></td></tr>
    <tr><td>Output</td><td>Caf\#u{E9} Menu</td><td>box 2 right</td><td>boundary right</td><td></td><td></td></tr>
    </tbody></table>
    <p><strong>Notes</strong></p>
    <div style="margin-left:0rem">• <strong>A2</strong> — Needs <strong>review</strong> | see <em>spec</em> second line\#r third</div>
    <h2>Concepts</h2>
    <table><thead>
    <tr><th>Term</th><th>Kind</th><th>Used</th><th>Occurs on</th><th>Definition</th></tr></thead><tbody>
    <tr><td>Cafe\#u{301} Menu</td><td>data</td><td>1</td><td>A0\#u{A0}obj</td><td><em>undefined</em></td></tr>
    <tr><td>Caf\#u{E9} Menu</td><td>data</td><td>1</td><td>A0\#u{A0}obj</td><td><em>undefined</em></td></tr>
    <tr><td>Order</td><td>data</td><td>2</td><td>A-0\#u{A0}obj, A0\#u{A0}obj</td><td>Has a | pipe and \| escaped</td></tr>
    <tr><td>Plan \| Actual * <code>code</code> <em>it</em> &lt;&amp;&gt;</td><td>data</td><td>1</td><td>A0\#u{A0}obj</td><td><em>undefined</em></td></tr>
    <tr><td>Plan | Actual</td><td>data</td><td>1</td><td>A-0\#u{A0}obj</td><td><em>undefined</em></td></tr>
    <tr><td>Run Plant</td><td>activity</td><td>1</td><td>A0\#u{A0}act</td><td><em>undefined</em></td></tr>
    <tr><td>Ship \| *Product* _<em>x</em>_</td><td>activity</td><td>1</td><td>A1\#u{A0}act</td><td><em>undefined</em></td></tr>
    <tr><td>Unused | term</td><td>other</td><td>0</td><td>—</td><td><strong>Bold</strong> def with <code>code</code> and a<em>b</em>c line two</td></tr>
    </tbody></table>
    <h3>Label elaboration</h3>
    <p>Places where the drawn text differs from the concept it denotes — legitimate under FIPS 183 §3.3.2.4.</p>
    <table><thead>
    <tr><th>Where</th><th>Reads</th><th>Concept</th></tr></thead><tbody>
    <tr><td>A0 arrow</td><td>Order Records</td><td>Order</td></tr>
    </tbody></table>
    <p><em>1 concept(s) defined but not used: Unused | term.</em></p>
    <h2>Rule check</h2>
    <p>7 error(s), 10 warning(s).</p>
    <table><thead>
    <tr><th>Severity</th><th>Diagram</th><th>Rule</th><th>Detail</th></tr></thead><tbody>
    <tr><td>error</td><td>A-0</td><td><code>box-output</code></td><td>A0 has no output. Every IDEF0 box requires at least one output arrow from its right.</td></tr>
    <tr><td>error</td><td>A0</td><td><code>icom-orphan</code></td><td>A0: boundary output “Caf\#u{E9} Menu” on the right has no matching arrow on parent box A0. Connect it on A-0 or tunnel it.</td></tr>
    <tr><td>error</td><td>A-0</td><td><code>icom-missing</code></td><td>A-0: I1 “Order” on box A0 (left) does not appear as a boundary arrow on A0. Add it there or tunnel it.</td></tr>
    <tr><td>error</td><td>A0</td><td><code>box-name</code></td><td>Box 2 on A0 is unnamed. Box names are active verb phrases.</td></tr>
    <tr><td>error</td><td>A0</td><td><code>box-control</code></td><td>A1 has no control. Every IDEF0 box requires at least one control arrow on its top.</td></tr>
    <tr><td>error</td><td>A0</td><td><code>arrow-label</code></td><td>An unlabelled input arrow on A0. Arrow labels are noun phrases.</td></tr>
    <tr><td>error</td><td>A0</td><td><code>arrow-dangling</code></td><td>An arrow on A0 points at a box that no longer exists.</td></tr>
    <tr><td>warning</td><td>A-0</td><td><code>model-viewpoint</code></td><td>The model states no viewpoint. Every IDEF0 model must declare one.</td></tr>
    <tr><td>warning</td><td>A0</td><td><code>icom-concept-mismatch</code></td><td>A0: C1 “Plan \| Actual * <code>code</code> <em>it</em> &lt;&amp;&gt;” is bound to a different concept than parent box A0 carries as “Plan | Actual”. The two ends of an ICOM pair should denote the same object (§3.3.2.4).</td></tr>
    <tr><td>warning</td><td>A0</td><td><code>icom-relabel</code></td><td>A0: C1 reads “Plan \| Actual * <code>code</code> <em>it</em> &lt;&amp;&gt;” where parent box A0 carries “Plan | Actual”. Fine if it details that arrow — otherwise the two have drifted apart.</td></tr>
    <tr><td>warning</td><td>A0</td><td><code>decomp-count</code></td><td>A0 has 2 box(es). A decomposition should have 3–6; fewer than 3 adds no detail.</td></tr>
    <tr><td>warning</td><td>A0</td><td><code>concept-undefined</code></td><td>“Cafe\#u{301} Menu” (data) is used 1× but has no glossary definition.</td></tr>
    <tr><td>warning</td><td>A0</td><td><code>concept-undefined</code></td><td>“Caf\#u{E9} Menu” (data) is used 1× but has no glossary definition.</td></tr>
    <tr><td>warning</td><td>A0</td><td><code>concept-undefined</code></td><td>“Plan \| Actual * <code>code</code> <em>it</em> &lt;&amp;&gt;” (data) is used 1× but has no glossary definition.</td></tr>
    <tr><td>warning</td><td>A-0</td><td><code>concept-undefined</code></td><td>“Plan | Actual” (data) is used 1× but has no glossary definition.</td></tr>
    <tr><td>warning</td><td>A-0</td><td><code>concept-undefined</code></td><td>“Run Plant” (activity) is used 1× but has no glossary definition.</td></tr>
    <tr><td>warning</td><td>A0</td><td><code>concept-undefined</code></td><td>“Ship \| *Product* _<em>x</em>_” (activity) is used 1× but has no glossary definition.</td></tr>
    </tbody></table>
    <hr>
    <p><em>Generated by IDEF0 Modeler on DATE.</em></p>
    """#

    private static let quirksMarkdown = #"""
    # Untitled IDEF0 Model

    | | |
    |---|---|
    | Author |  |
    | Project |  |
    | Status | WORKING |
    | Created | 2026-01-02 |
    | Revised | 2026-01-03 |

    **Purpose.** |
    ||
    |x
    |\#u{20}\#u{20}
    | - |
    \|x|
      |x|y|
    | a \| b | c\\|d |
    |\#u{1F642}
    text
    |`a|b`|

    **Viewpoint.** View

    ## Node index


    ## Diagrams

    ### A-0 —\#u{20}

    **Activities**

    | Box | Node | Name | Decomposed |
    |---|---|---|---|

    **Arrows**

    | Role | Label | From | To | ICOM | Tunnel |
    |---|---|---|---|---|---|

    ## Rule check

    1 error(s), 1 warning(s).

    | Severity | Diagram | Rule | Detail |
    |---|---|---|---|
    | error | A-0 | `ctx-single-box` | The A-0 context diagram holds 0 boxes; it must hold exactly one. |
    | warning | A-0 | `model-title` | The model has no title. |

    ---

    _Generated by IDEF0 Modeler on DATE._
    """#

    /// `line.slice(1, -1)` leaves the web app half of the emoji in `|🙂`: a lone
    /// high surrogate, which the saved UTF-8 file holds as U+FFFD.
    private static let quirksBody = #"""
    <h1>Untitled IDEF0 Model</h1>
    <table><thead>
    <tr><th>Author</th><th></th></tr></thead><tbody>
    <tr><td>Project</td><td></td></tr>
    <tr><td>Status</td><td>WORKING</td></tr>
    <tr><td>Created</td><td>2026-01-02</td></tr>
    <tr><td>Revised</td><td>2026-01-03</td></tr>
    </tbody></table>
    <p><strong>Purpose.</strong> |</p>
    <table><thead>
    <tr><th></th></tr></thead><tbody>
    </tbody></table>
    <p>|x|</p>
    <p>  |x|y|</p>
    <table><thead>
    <tr><th>a | b</th><th>c\|d</th></tr></thead><tbody>
    <tr><td>\#u{FFFD}</td></tr>
    </tbody></table>
    <p>text</p>
    <table><thead>
    <tr><th>`a</th><th>b`</th></tr></thead><tbody>
    </tbody></table>
    <p><strong>Viewpoint.</strong> View</p>
    <h2>Node index</h2>
    <h2>Diagrams</h2>
    <h3>A-0 —</h3>
    <p><strong>Activities</strong></p>
    <table><thead>
    <tr><th>Box</th><th>Node</th><th>Name</th><th>Decomposed</th></tr></thead><tbody>
    </tbody></table>
    <p><strong>Arrows</strong></p>
    <table><thead>
    <tr><th>Role</th><th>Label</th><th>From</th><th>To</th><th>ICOM</th><th>Tunnel</th></tr></thead><tbody>
    </tbody></table>
    <h2>Rule check</h2>
    <p>1 error(s), 1 warning(s).</p>
    <table><thead>
    <tr><th>Severity</th><th>Diagram</th><th>Rule</th><th>Detail</th></tr></thead><tbody>
    <tr><td>error</td><td>A-0</td><td><code>ctx-single-box</code></td><td>The A-0 context diagram holds 0 boxes; it must hold exactly one.</td></tr>
    <tr><td>warning</td><td>A-0</td><td><code>model-title</code></td><td>The model has no title.</td></tr>
    </tbody></table>
    <hr>
    <p><em>Generated by IDEF0 Modeler on DATE.</em></p>
    """#
}
