// Text deliverables: the node index, activity list, ICOM tables and glossary,
// as Markdown or as a self-contained HTML document.

import { downloadText, slugify, escapeXml } from '../util.js';
import { ROLE_LABEL } from '../model/types.js';
import { arrowRole, boxNode, childDiagram, contextDiagram, diagramTree, icomCodes, sortedBoxes } from '../model/model.js';
import { validate, summarize } from '../model/validate.js';
import { conceptUsage, occurrencesOf, unusedConcepts, driftedOccurrences } from '../model/concepts.js';

export function toMarkdown(model) {
  const L = [];
  const push = (...s) => L.push(...s);

  push(`# ${model.title || 'Untitled IDEF0 Model'}`, '');
  push('| | |', '|---|---|');
  push(`| Author | ${md(model.author)} |`);
  push(`| Project | ${md(model.project)} |`);
  push(`| Status | ${md(model.status)} |`);
  push(`| Created | ${md(model.created)} |`);
  push(`| Revised | ${md(model.revised)} |`);
  push('');
  push('**Purpose.** ' + (model.purpose.trim() || '_not stated_'), '');
  push('**Viewpoint.** ' + (model.viewpoint.trim() || '_not stated_'), '');

  push('## Node index', '');
  const ctx = contextDiagram(model);
  const indexLines = [];
  // Every box is listed; a detail diagram already on the path — a
  // decomposition cycle, reported by the rule check — is not entered again.
  const path = new Set();
  const walkIndex = (dg, depth) => {
    path.add(dg.id);
    for (const b of sortedBoxes(dg)) {
      indexLines.push(`${'  '.repeat(depth)}- **${boxNode(dg, b)}** ${b.name || '_(unnamed)_'}`);
      const child = childDiagram(model, b);
      if (child && !path.has(child.id)) walkIndex(child, depth + 1);
    }
    path.delete(dg.id);
  };
  walkIndex(ctx, 0);
  push(...indexLines, '');

  push('## Diagrams', '');
  for (const { diagram: dg, depth } of diagramTree(model)) {
    push(`### ${dg.node} — ${dg.title || model.title}`, '');
    if (dg.cNumber) push(`C-number: \`${dg.cNumber}\``, '');

    push('**Activities**', '');
    push('| Box | Node | Name | Decomposed |', '|---|---|---|---|');
    for (const b of sortedBoxes(dg)) {
      push(`| ${b.number} | ${boxNode(dg, b)} | ${md(b.name) || '_(unnamed)_'} | ${childDiagram(model, b) ? 'yes' : 'no'} |`);
    }
    push('');

    const codes = icomCodes(model, dg);
    push('**Arrows**', '');
    push('| Role | Label | From | To | ICOM | Tunnel |', '|---|---|---|---|---|---|');
    for (const a of dg.arrows) {
      const code = codes[`${a.id}:from`] || codes[`${a.id}:to`] || '';
      push(`| ${ROLE_LABEL[arrowRole(a)]} | ${md(a.label) || '_(unlabelled)_'} | ${endDesc(dg, a.from)} | ${endDesc(dg, a.to)} | ${code} | ${a.tunnelFrom || a.tunnelTo ? 'yes' : ''} |`);
    }
    push('');

    const notes = sortedBoxes(dg).filter((b) => b.note.trim());
    if (notes.length) {
      push('**Notes**', '');
      for (const b of notes) push(`- **${boxNode(dg, b)}** — ${md(b.note)}`);
      push('');
    }
  }

  if (model.glossary.length) {
    // The concept registry, with where each concept is used. This is the part
    // of the report meant to be read by something other than a person.
    const usage = conceptUsage(model);
    push('## Concepts', '');
    push('| Term | Kind | Used | Occurs on | Definition |', '|---|---|---|---|---|');
    for (const g of model.glossary) {
      const occ = occurrencesOf(model, g.id);
      const where = occ.map((o) => `${o.node}\u00a0${o.kind === 'box' ? 'act' : 'obj'}`).join(', ');
      push(`| ${md(g.term)} | ${g.kind} | ${usage.get(g.id) || 0} | ${where || '—'} | ${md(g.definition) || '_undefined_'} |`);
    }
    push('');

    const drift = driftedOccurrences(model);
    if (drift.length) {
      push('### Label elaboration', '');
      push('Places where the drawn text differs from the concept it denotes — legitimate under FIPS 183 §3.3.2.4.', '');
      push('| Where | Reads | Concept |', '|---|---|---|');
      for (const d of drift) push(`| ${d.node} ${d.kind === 'box' ? 'activity' : 'arrow'} | ${md(d.text)} | ${md(d.term)} |`);
      push('');
    }

    const unused = unusedConcepts(model);
    if (unused.length) {
      push(`_${unused.length} concept(s) defined but not used: ${unused.map((g) => md(g.term)).join(', ')}._`, '');
    }
  }

  const issues = validate(model);
  const s = summarize(issues);
  push('## Rule check', '');
  push(`${s.errors} error(s), ${s.warnings} warning(s).`, '');
  if (issues.length) {
    push('| Severity | Diagram | Rule | Detail |', '|---|---|---|---|');
    for (const i of issues) {
      push(`| ${i.severity} | ${model.diagrams[i.diagramId]?.node || '—'} | \`${i.code}\` | ${md(i.message)} |`);
    }
    push('');
  }

  push('---', '', `_Generated by IDEF0 Modeler on ${new Date().toISOString().slice(0, 10)}._`);
  return L.join('\n');
}

function endDesc(dg, e) {
  if (e.type === 'boundary') return `boundary ${e.side}`;
  const b = dg.boxes.find((x) => x.id === e.boxId);
  return b ? `box ${b.number} ${e.side}` : 'missing box';
}

const md = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();

export function saveMarkdown(model) {
  const name = `${slugify(model.title)}-report.md`;
  downloadText(toMarkdown(model), name, 'text/markdown');
  return name;
}

export function toHtml(model) {
  const body = markdownToHtml(toMarkdown(model));
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeXml(model.title)} — IDEF0 report</title>
<style>
body{font:14px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  max-width:60rem;margin:2.5rem auto;padding:0 1.5rem;color:#1c2024}
h1{font-size:1.8rem;border-bottom:2px solid #1f5fa9;padding-bottom:.4rem}
h2{font-size:1.25rem;margin-top:2.2rem;border-bottom:1px solid #d7dbe0;padding-bottom:.3rem}
h3{font-size:1.05rem;margin-top:1.6rem;color:#1f5fa9}
table{border-collapse:collapse;width:100%;margin:.6rem 0 1.2rem}
th,td{border:1px solid #d7dbe0;padding:.35rem .6rem;text-align:left;vertical-align:top}
th{background:#f2f4f7;font-size:.86rem;text-transform:uppercase;letter-spacing:.04em}
code{background:#f2f4f7;padding:.1rem .3rem;border-radius:3px;font-size:.9em}
li{margin:.1rem 0}
em{color:#6b7280}
hr{border:0;border-top:1px solid #d7dbe0;margin:2rem 0}
</style></head><body>${body}</body></html>`;
}

export function saveHtml(model) {
  const name = `${slugify(model.title)}-report.html`;
  downloadText(toHtml(model), name, 'text/html');
  return name;
}

/** Just enough Markdown for the report this module produces. */
function markdownToHtml(mdText) {
  const lines = mdText.split('\n');
  const out = [];
  let inTable = false, headerDone = false;

  const inline = (s) => escapeXml(s)
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/_([^_]+)_/g, '<em>$1</em>')
    .replace(/\\\|/g, '|');

  const closeTable = () => { if (inTable) { out.push('</tbody></table>'); inTable = false; headerDone = false; } };

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (/^\|/.test(line)) {
      const cells = line.slice(1, -1).split(/(?<!\\)\|/).map((c) => c.trim());
      if (/^[\s|:-]+$/.test(line)) { continue; }
      if (!inTable) { out.push('<table><thead>'); inTable = true; headerDone = false; }
      if (!headerDone) {
        out.push(`<tr>${cells.map((c) => `<th>${inline(c)}</th>`).join('')}</tr></thead><tbody>`);
        headerDone = true;
      } else {
        out.push(`<tr>${cells.map((c) => `<td>${inline(c)}</td>`).join('')}</tr>`);
      }
      continue;
    }
    closeTable();
    if (/^### /.test(line)) out.push(`<h3>${inline(line.slice(4))}</h3>`);
    else if (/^## /.test(line)) out.push(`<h2>${inline(line.slice(3))}</h2>`);
    else if (/^# /.test(line)) out.push(`<h1>${inline(line.slice(2))}</h1>`);
    else if (/^---$/.test(line)) out.push('<hr>');
    else if (/^(\s*)- /.test(line)) {
      const indent = (line.match(/^\s*/)[0].length) / 2;
      out.push(`<div style="margin-left:${indent * 1.4}rem">• ${inline(line.replace(/^\s*- /, ''))}</div>`);
    } else if (line.trim()) out.push(`<p>${inline(line)}</p>`);
  }
  closeTable();
  return out.join('\n');
}
